<a href="https://colab.research.google.com/github/davidmena1239/AIS-Python-Workshop/blob/main/Python_Workshop_1_(Fall_2021).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Welcome to our beginner Python Workshop!

###Comments

In [47]:
#Single Line Comments
#To make a single-line comment, begin the line with a '#' key. Anything after the # will be considered a comment if it's on the line
#Doing this will not affect the output of your code

#Multi Line Comments or Doc Strings

""" """ or ''' '''
''' To make multi-line comments,
use three quotation marks  
at the start and the end of your notes '''

#Example:

  #This is a single line comment

'''This is 
    a multi 
    line comment'''

'This is \n    a multi \n    line comment'

##The print function and data types
##Data Type 1 - Strings ('str')

In [ ]:
#This line of code is outputting a 'string' or 'str' data type.
#Strings MUST be encapsulated with quotations "" or ''

print("Hello World")

#We may check the data type being used with the type() function 

print(type("Hello World"))

#The following would also be considered strings

print(type("I love AIS"))
print(type("Baruch student's are smart")) #Note: Sometimes you want to use words with apostrophes, so use double quotes instead of a single quotes 
print(type("AIS is the best"))

Hello World
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


## Data Type 2 - Integers ('int')

In [ ]:
#Integers refer to counting numbers (i.e 0, 1, 2...) and negative #numbers (i.e. -3, -2, -1, ) with NO decimals
#They DO NOT need to be encapsulated in quotations
#Below is an example of a integer

print(55)
print(type(55))
print(-55)
print(type(-55))

55
<class 'int'>
-55
<class 'int'>


##Data Type 3 - Floats ('float')

In [ ]:
''' Floats refer to numbers (positve and negative) which contain decimals
Like integers, they DO NOT need to be encapsulated in quotations '''

print(69.9)
print(type(69.9))
print(24.0)
print(type(24.0))


#Fractions are considered floats REGARDLESS of whether they have a remainder or not

print(-69/9)
print(type(-69/9))

#Note that if you divide two integers the result will ALWAYS be a FLOAT!

print(30/10)
print(type(30/10))

#Remember: any numbers encapsultated in parenthesees ("" or '') are STRINGS
#For example:

print("69.9")
print(type("69.9"))

69.9
<class 'float'>
24.0
<class 'float'>
-7.666666666666667
<class 'float'>
3.0
<class 'float'>
69.9
<class 'str'>


## Data Type 4- Booleans ('bool')

In [ ]:
'''Booleans can either refer to the words True or False
They DO NOT need to be encapsulated in quotation marks
 '''

print(type(True))
print(type(False))

<class 'bool'>
<class 'bool'>


In [ ]:
#Boolean Expressions

print((1 == 1))

print((1 != 1)) #Note: != is refers to 'not equal'

print((2 > 1)) 

print((2.0 <= 3.0))

print(("AIS" == "AS"))

True
False
True
True
False


## Mathematical Operations

In [ ]:
# (+) Addition

print(1+1)

2


In [ ]:
# (-) Subtraction

print(2-1)

1


In [ ]:
# (/) Division

print(3/2)


1.5


In [ ]:
# (*) Multiplication

print(4*2)

8


In [49]:
# (%) Modulus (Remainder) - This will divide the two numbers and return the remainder

print(10 % 3)

1


In [2]:
# (**) Exponent - Two multiplication operators make an exponent operator

print(5**2)

25


## Variables

In [56]:
'''
Can be any type (Float, string, int, etc.)

The left side is the variable and the right side is the value we want to assign to the variable.

Rules of variables 
1. Don't make variables keywords (ex. if, else, return, True, etc) You can look up list of python keywords for more examples.

2. Your variable name must start with a letter from a-z, A-Z, or an underscore character. (NO numbers in the beginning of your variable name)

3. Make variable names that make sense with what's being assigned to them (ex. BondPrice, CapRate) 

4. Variables are case sensitive (Apple is NOT the same as apple)

5. A variable name CANNOT contain spaces 
'''

"\nCan be any type (Float, string, int, etc.)\n\nThe left side is the variable and the right side is the value we want to assign to the variable.\n\nRules of variables \n1. Don't make variables keywords (ex. if, else, return, True, etc) You can look up list of python keywords for more examples.\n\n2. Your variable name must start with a letter from a-z, A-Z, or an underscore character. (NO numbers in the beginning of your variable name)\n\n3. Make variable names that make sense with what's being assigned to them (ex. BondPrice, CapRate) \n\n4. Variables are case sensitive (Apple is NOT the same as apple)\n\n5. A variable name CANNOT contain spaces \n"

In [57]:
#Examples of variables

ex = "word"
print(ex)
print(type(ex))

word
<class 'str'>


In [ ]:
ex2 = 4.0
print(ex2)
print(type(ex2))

4.0
<class 'float'>


In [ ]:
width = 10
length = 5 
area = width * length

print(area)
print(type(area))

50
<class 'int'>


In [ ]:
#You can also redefine variables 

var1 = 3.0
print(var1)

3.0


In [3]:
var1 = 3.5
print(var1)

3.5


In [50]:
#We can reassign variables to another data type. This can be done with casting 
#5 is an integer, but lets turn it into a float

ex3 = 5
print(type(ex3))
print(ex3)

<class 'int'>
5


In [51]:
ex4 = float(ex3)
print(type(ex4))
print(ex4)

<class 'float'>
5.0


In [52]:
#Another example
num = 55
print(type(num))
print(num)

<class 'int'>
55


In [58]:
num2 = str(num)
print(type(num2))
print(num2)

<class 'str'>
55


In [54]:
#You can also do this without variables

print(type(4))
print(type(str(4)))

<class 'int'>
<class 'str'>


In [55]:
print(type(10.45))
print(type(int(10.45)))

<class 'float'>
<class 'int'>


In [93]:
print(bool("Hi"))

print(type(bool("Hi")))

print(bool(""))

True
<class 'bool'>
False


In [94]:
print(bool(10.323234))

print(type(bool(0)))

print(bool(0))

True
<class 'bool'>
False


In [72]:
print(type(True))

print(str(True))

print(type(str(True)))

<class 'bool'>
True
<class 'str'>


In [97]:
print(type(True))

print(float(True))

print(type(float(True)))

<class 'bool'>
1.0
<class 'float'>


In [96]:
print(type(False))

print(int(False))

print(type(int(False)))

<class 'bool'>
0
<class 'int'>


In [102]:
#It won't work for some things, like you can't change a string into an integer unless it's a number in the string

print(type(int("David")))

ValueError: ignored

In [104]:
#This will work because there's a number in the string

print(int("55"))

print(type(int("55")))

55
<class 'int'>


##Input function

In [6]:
#Input functions allows a user to input information into our program. 

input("Enter your first and last name: ")

Enter your first and last name: David Mena


'David Mena'

In [8]:
#We'll be able take this information, assign it to a variable, and then do something with that variable.

name = input("Enter your first and last name: ")
print("Hey " + name + "!")

Enter your first and last name: David Mena
Hey David Mena!


In [10]:
'''The print statement above uses concatenation to combine the elements. 
NOTE: You can only concatenate a string with another string. 
For example, if I want to combine a variable that holds an integer with a string, it will give me an error. '''

print("David is " + 21)

TypeError: ignored

In [11]:
#You can get around this by turning the element into a string. 

print("David is " + str(21))

David is 21


In [13]:
#You can also combine variables with a comma. For example:

x = 25
a = "David" 
print(a, "is", x)

David is 25


In [14]:
#if you did this with concatenation, you'd have to turn x into a string, for example:

print(a + " is " + str(x))

David is 25


## Lists


In [2]:
'''We make a list the same way we make variables. 
When we make a list, we use open and close square brackets []. Python will know you're making a list when it sees this. 
For example: '''

coworkers = ["Jim", "Dwight", "Michael", "Pam", "Kevin"]

In [3]:
#You can put any data type into a list (strings, integers, booleans, etc).
#We can make this list below and python will accept it.

whatever = ["David", 1234, False]

In [4]:
#Let's go back to the original list we made and work on it. print(coworkers) will print the list.

print(coworkers) 

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin']


In [6]:
'''We can access specific elements through indexing.
Each element in the list has a specific index and they start from 0. 
Lets say we want to get Jim from the list.'''

print(coworkers[0])

Jim


In [7]:
#The code below will give us Michael

print(coworkers[2]) 

Michael


In [21]:
'''You can also access elements backwards through negative indexing.
When we perform negative indexing, we start from -1, not 0.'''

print(coworkers[-1])

Kevin


In [22]:
#if you want Pam you can do 

print(coworkers[-2])

Pam


In [23]:
#for reference
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin']


In [8]:
'''Another way we can access elements is through slicing. We can achieve this by using a colon (:). 
There is a special case we MUST make note of when slicing lists, the index number we put after the colon.  
When slicing, python will grab all the elements up to but NOT including the index after the colon.
For example: '''

print(coworkers[1:4])

#The statement above grabbed index 1, 2, and 3, but not 4. 

['Dwight', 'Michael', 'Pam']


In [10]:
#Leaving the number blank before or after the colon means it will get everything. For example:

print(coworkers[:])

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin']


In [14]:
#Lets say I want to get the last 2 elements of the list, we can do 
#This will get the third element of the list and all of the elements after. 

print(coworkers[3:])

['Pam', 'Kevin']


In [ ]:
print(coworkers[:3])

['Jim', 'Dwight', 'Michael']


In [ ]:
#We can also modify elements in a list. All we'll have to do is access the element and set it equal to whatever you want.
#This works because lists are mutable, which means we can change them.

coworkers[1] = "Oscar" 
print(coworkers)

#Now Dwight was replaced with Oscar in the list.

['Jim', 'Oscar', 'Michael', 'Pam', 'Kevin']


##List functions

In [22]:
#There are functions already in python that let us do certain things to our lists.
#Let's bring back our coworkers list and make a list of numbers.

numbers = [10, 3, 100, 46, 58, 23]
coworkers = ["Jim", "Dwight", "Michael", "Pam", "Kevin"]

In [23]:
#One is called the .extend() function which lets you extend a list with another list.

coworkers.extend(numbers)
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin', 10, 3, 100, 46, 58, 23]


In [48]:
#Another function is .append() which lets you add an individual element to the end of a list.
#We'll run the original coworkers list to get rid of the numbers from the extend function.

coworkers = ["Jim", "Dwight", "Michael", "Pam", "Kevin"]

In [49]:
#Now lets append it with another coworker
coworkers.append("Andy")
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin', 'Andy']


In [50]:
#.insert() takes 2 arguments (index, element) and replaces the element at the index position with the element of your choice.
#It doesn't replace the element at the original index, it moves the original element over to a new index position.

coworkers.insert(3, "Kelly")
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Kelly', 'Pam', 'Kevin', 'Andy']


In [51]:
#.remove() removes the element of your choice. The element you want to remove is the argument.

coworkers.remove("Kevin")
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Kelly', 'Pam', 'Andy']


In [53]:
#.pop() removes the last element in the list. It can take no arguments or take an index position argument and will remove the element at the index position.

coworkers.pop()
print(coworkers)

coworkers.pop(0)
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Kelly']
['Dwight', 'Michael', 'Kelly']


In [56]:
#we'll run the original coworkers list again to get our elements back

coworkers = ["Jim", "Dwight", "Michael", "Pam", "Kevin"]

In [57]:
#.index() tells you the index of the element you’re trying to find in the list. Accepts the element as the argument.

coworkers.index("Dwight")

1

In [58]:
'''.copy() will copy the list you choose to put before the dot.
Lets make a variable called coworkers2.
When we use .copy(), coworkers2 will have all the same attributes as coworkers since it's a copy.'''

coworkers2 = coworkers.copy()
print(coworkers2)

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin']


In [59]:
#Let's use the numbers list we made along with the coworkers list for these remaining functions.

#.sort() will sort a list in ascending or alphabetical order. For example:

print(coworkers)
coworkers.sort()
print(coworkers)

['Jim', 'Dwight', 'Michael', 'Pam', 'Kevin']
['Dwight', 'Jim', 'Kevin', 'Michael', 'Pam']


In [60]:
#Another example

print(numbers)
numbers.sort()
print(numbers)

[10, 3, 100, 46, 58, 23]
[3, 10, 23, 46, 58, 100]


In [61]:
#.reverse() will reverse the order of the list. For example:

print(coworkers)
coworkers.reverse()
print(coworkers)

['Dwight', 'Jim', 'Kevin', 'Michael', 'Pam']
['Pam', 'Michael', 'Kevin', 'Jim', 'Dwight']


In [62]:
#Another example

print(numbers)
numbers.reverse()
print(numbers)

[3, 10, 23, 46, 58, 100]
[100, 58, 46, 23, 10, 3]


In [63]:
#.clear() removes everything from the list

print(coworkers)
coworkers.clear()
print(coworkers)

['Pam', 'Michael', 'Kevin', 'Jim', 'Dwight']
[]


In [64]:
#Another example

print(numbers)
numbers.clear()
print(numbers)

[100, 58, 46, 23, 10, 3]
[]


##NumPy (Numerical Python) - If time permits

In [66]:
import numpy as np 

In [67]:
#Making arrays is simple in Numpy, we just type np.array

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [68]:
#We can set it to a variable

a = np.array([1, 2, 3, 4])

print(type(a))

print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [69]:
#We can use indexing and slicing to get elements from it like a list 

print(a[0])

print(a[-1])

print(a[0], a[1], a[2], a[3])

print(a[1:3])

1
4
1 2 3 4
[2 3]


In [70]:
#can change elements in the array

a[1] = 8
print(a)

[1 8 3 4]


In [71]:
#2 dimensional arrays

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(b)

[[1 2 3]
 [4 5 6]]


In [72]:
#.shape shows you the number of rows and columns in an array, respectively

b.shape

(2, 3)

In [73]:
# This is a multi dimensional array. We can go thorugh it with index and slicing

c = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [74]:
#The index goes by rows, then columns. 

print(c[1]) #will give the row at index 1

[4 5 6]


In [75]:
print(c[1][0]) #will give us the element from row index 1, column index 0

print(c[1, 0]) #Does the same thing as above. 

4
4


In [76]:
#Slicing lets us get the first 2 rows

c[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
#We can slice through both dimensions. 

c[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
#can see statistics of an array with numpy

a = np.array([1, 2, 3, 4])
print(a)

print(a.sum())

print(a.mean())

print(a.std())

[1 2 3 4]
10
2.5
1.118033988749895


In [79]:
#we can also do it for multi dimensional arrays
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(b)

print(b.sum())

#Axis = 0 is referring to the columns and axis = 1 refers to the rows
print(b.sum(axis = 0))
print(b.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


#Thank you for joining our Python Workshop #1
##Please join our next one next Tuesday!!